### ISSUE TITLE
Bug: AddOns that are enabled but were not pickedup by AddonSuite

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-suite#13]
This isssue was created from:
Synchronized enabled addons checklist against current enabled/disabled addons state #5

>Doing great so far.  Are you still working on synchronizing the addon with existing addons per character?
>I have attached a screenshots
showing what I am talking about.  The addons were already enabled but were not
picked up by AddonSuite.  Thanks!

![World Of Warcraft Screenshot 2024 03 29 - 11 45 15 42](https://github.com/kapresoft/wow-addon-suite/assets/34355842/12ea50ee-a51d-4f1c-bf67-97f47bc1cee8)
![World Of Warcraft Screenshot 2024 03 29 - 11 45 39 82](https://github.com/kapresoft/wow-addon-suite/assets/34355842/0e475f54-d301-400a-9292-c739d169fa31)

_Originally posted by @msc6399 in https://github.com/kapresoft/wow-addon-suite/issues/5#issuecomment-2027409761_

**Comment by nfet** [comment]
I'm not sure what I was thinking at the time but I decided not to include the "on demand" addons.

https://github.com/kapresoft/wow-addon-suite/blob/f6878e2c63dab1d20431257f6397c2727855deff/Core/Lib/API/API.lua#L72

**Comment by msc6399** [comment]
Is this what you were intending?
![Screenshot (4)](https://github.com/kapresoft/wow-addon-suite/assets/34355842/3fd094f1-e112-464c-912a-d70ee5077547)

**Comment by nfet** [comment]
Yes, but the popup is annoying to some or most(?) so I will make an opyion for it and disable by default. I still need to revisit and include on-demand addons if selected.

The popup works for me because if my selected profile is out of sync, I want to reload to get it sync. In working on #16.

**Comment by msc6399** [comment]
Could not figure out why disable addons that were already enable?

**Comment by nfet** [comment]
I have not started working on this yet.

**Comment by msc6399** [comment]
gotcha. good work.

**Comment by nfet** [comment]
Hi There,
Is this still an issue with the latest release?
