### ISSUE TITLE
dialogue box after login - enable old addons / disable current addons ?

### ISSUE THREAD

**Issue by ux-paul-grossmann** [kapresoft/wow-addon-suite#16]
**Describe the bug**
Since a recent update(don't know which tbh), with any char when I'm logging in, I get this dialogue box (screenshot) which asks whether I want to enable previously deleted Addons AND asks me to disable my current active ones. The proposed Addons to be enabled, were deleted days before. 

**To Reproduce**

1. Install Addon Suite
2. Create new profile - conceptual -
3. Select Addons checkmarks
4. Log onto any character
5. Copy and select profile - conceptual - for any char
6. Updating Addon Suite via CurseForge recently
7. Starting WoW Classic SoD, logging onto any char
9. Getting Long Listed Dialogue displayed
10. Select profile - conceptual - for any char
11. Getting Short Listed Dialogue displayed
12. Dialogue Box is displayed upon loggin in on any char now

**Expected behavior**
Just work, without dialog request.
Function to handle the leftovers of removed Addons?

**Screenshots**
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/43357149-a04f-4e7a-be94-abe12b186117)
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/601cb4fb-5ac9-4ba5-81c4-2fd998fa1433)
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/f36ee107-0019-486d-b2a5-cb70c7a18e46)
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/01c50cc8-edaa-4352-87b3-b5718f1be0b2)

**Operating System**
- OS: [MacOS Sonoma]
- Version [Classic Season of Discovery]

**Additional context**
General > Confirm Reloads - doesn't trigger Confirmation Dialogue, instead it instantly reloads UI

**Comment by nfet** [comment]
I'm working the fix now.

Question for this:
> General > Confirm Reloads - doesn't trigger Confirmation Dialogue, instead it instantly reloads UI

Is this for the "Apply and Reload UI" button? I had meant for this be immediate since the player has to click this button manually.  I have changed the help text to be more clear. All others reloads will prompt for a confirmation dialog (edit: if configured). Let me know if you are referring to some other scenario/bug.

![apply and reload](https://github.com/kapresoft/wow-addon-suite/assets/1599306/bf5eb8a8-15e1-4dd7-8ae1-0cd59bb24daf)

**Comment by nfet** [comment]
Also just to add, if the user checks/unchecks addons on this tab and close the dialog without clicking "Apply and Reload", the user will be prompted for a reload.

**Comment by ux-paul-grossmann** [comment]
> I'm working the fix now.
> 
> Question for this:
> 
> > General > Confirm Reloads - doesn't trigger Confirmation Dialogue, instead it instantly reloads UI
> 
> Is this for the "Apply and Reload UI" button? I had meant for this be immediate since the player has to click this button manually. I have changed the help text to be more clear. All others reloads will prompt for a confirmation dialog (edit: if configured). Let me know if you are referring to some other scenario/bug.
> ![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/a7daca64-e51c-4f23-8c07-0349749e4fc8)

Hi,

European Time Zone here, Germany^^

Actually this is what I meant:
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/6198f000-af05-4395-bee6-2d545fd6d0bd)


if I set checkmark 
on "Confirm Reloads" 
then 
when I click on 
"Apply and Reload"-btn
I expect appearing prompt (dialogue) to confirm myself manually 
as is labeled in the description of the tooltip.

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/65ade4e3-74a4-4d5e-b866-83ccc78c8def)

Yet it(dialogue) doesn't show up for me.
It instantly reloads ui on click "Apply and Reload" btn regardless of the checkmark of "Confirm Reloads" 

Maybe a more human language label could be like "Ask me to confirm UI-Reloads" - As an idea.

The red status label doesn't change in the tooltip, when interacting with "Confirm Reloads" checkbox.

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/f94c593f-af63-4e69-8684-cae2a06b2a6d)


Additionally:
Just came home from work and updated the Addon via CurseForge. Started WoW and got this on login. Just curious, maybe there is missing information, context for the users above "Would you like to reload now to activate these changes? ..." Or maybe it makes sense in a non bugged scenario or its confusing.

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/b477eb0d-a414-4df2-9cd0-7090ed1ed14a)

Plus:

> Also just to add, if the user checks/unchecks addons on this tab and close the dialog without clicking "Apply and Reload", the user will be prompted for a reload.

Can't confirm this unfortunately. It just closes without prompting.

The Debugging Tab, I have checked everything, but it's not straightforward for the average user. Maybe it requires additional information on how to proceed. Maybe a record btn, then export as target format button or output in chat? idk actually. It displays log level and categories checkmarks. Maybe hide for average user or provide instructions to execute debugging process.

**Comment by AODfan** [comment]
I am still getting this pop-up when I log into any character and even in between load screens.  It is very annoying, why is it necessary to pop up all the time?

**Comment by nfet** [comment]
1.) There will be no change on how the "Apply and Reload" button works.

2.) "Confirm Reloads" option was meant for the Minimap menu profile switch, so this will be moved in the Minimap options tab.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/062a13af-cca5-4f39-931c-c5465b3c4bb7)

3.) For the popup - the functionality is to synchronize the state of the addons with the current selected profile. I will add checklist option to disable this by default.

Edit: Screenshot of the new option

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/2c5ee54c-cab0-4ef7-9f2e-e4cc045d4835)

Edit: Debugging tab
3) Debugging Tab is meant for developer(s) and will be hidden for users.

Thank you for using this Addon.

**Comment by ux-paul-grossmann** [comment]
Not sure, whether to open a new ticket, but Addon Suite isn't showing up in the interface > addons list. It is in the interface addons folder on hard drive, curseforge, also active in main menu > addons. Couldn't find any /addonsuite /as or those kind of chat commands in the addon suite description in curseforge app. 

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/d400fab7-9f5a-4d2c-8315-03c91aae22c8)

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/e2ff085a-df18-4084-9e77-c60bc99209e7)

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/426855b7-8203-4d83-adf6-169f0c504698)

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/e8b6310c-37de-4944-bfb2-41064f3f7525)

**Comment by nfet** [comment]
I removed this because UI is too small in the blizz options. Use the command line or minimap icon to open the config.

**Comment by nfet** [comment]
When you login for the first time and addon suit is enabled, you should see the command line option. Also hovering over the minimap icon will show the command line options.

**Comment by nfet** [comment]
When you login for the first time and addon suit is enabled, you should see the command line ootion. Also hovering over the minimap icon will show the command line options.

Also, use the tab character to complete the command.

Type /addon, then hit TAB

**Comment by nfet** [comment]
## Command Line Options

There are several places where a user will see the command line options

### Logging In

When first logging in, you will see this message on the console:

![addonsuite-cmdline](https://github.com/kapresoft/wow-addon-suite/assets/1599306/764875d7-66be-486e-84c8-a0ed50475dbe)

### Mouse Hover on Minimap Icon

On mouse hover over the minimap (see item 1 on the image), you will see this information:
Item 2 on the image is where the command line info is.  

You can RIGHT-click on the minimap icon to open the settings dialog.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/80b1638e-0d24-4eed-8fc7-1bd718c07e88)

Also, now that  you mentioned it and you've brought up a good point, I may rename the command line from `/addon-suite` to `/addonsuite`.

## New Feature:  Profile Sync Status Indicator

Now, the minimap icon will change to red if your selected profile isn't synced, alerting you right away! You can easily disable this alert from the options if you prefer.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/885f0700-1506-43f4-b3cf-e9818b22fc72)

### Reloading When Profile is Out of Sync

When the selected profile is out of sync, the user will see a new option to sync and reload the profile (ALT-Left-Click):

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/a08d43a1-674f-4582-b9b9-82ddc7b1e7e0)

**Comment by ux-paul-grossmann** [comment]
Thank you! I simply did not pay attention on the initial addons related msgs in the chat on login. Additionally the chat is quickly scrolling by, because of high populated server activity and godzillion ppl writing stuff. 

Believe, that the information from your last reply could help ppl in curseforge description and in all cases, like the removal of the addon suite ui from interface > addons and putting in another place in the minimap could be communicated via curseforge description to help people, to inform them :) 

Another thing, just from ux perspective. Your Addon Suite Logo
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/edc32a35-cd91-4ec9-b914-62706d34b345)

and instead the same logo/icon it somehow is a barrel :D Makes you think, why the barrel and not the icon from curseforge 🤔 :)
![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/4d52d493-69c2-40e0-b744-d19a755c55ea)

Consistency thing and kind of brand recognition, easy to grasp when there are not 1 mini map icon, but like 10+. 

The tooltip descriptions and hot keys look great!

**Comment by nfet** [comment]
My apologies on this.  You are essentially a beta-tester and I appreciate your feedback. As soon as the addon is stable, I will definitely be more careful on updates and inform users.  I will update the curseforge docs. I can thank you enough for all your feedback and patience.

So, true. Very good point :-)
>  Additionally the chat is quickly scrolling by, because of high populated server activity and godzillion ppl writing stuff.

> Believe, that the information from your last reply could help ppl in curseforge description and in all cases, like the removal of the addon suite ui from interface > addons and putting in another place in the minimap could be communicated via curseforge description to help people, to inform them :)

Icon: The icon is prelim, I plan to create a custom icon.
Logo: It's a preliminary logo because CurseForge requires you to create one when creating a project.  I'll create story for the logo/icon 👍 .   There's tons of work to do :-). 

I created the story for the command line optiont change to `/addonusage` #23 
Please keep creating bugs/enhancements as you see fit.

**Comment by nfet** [comment]
Created:  Consistency between Logo and Icon #24

**Comment by ux-paul-grossmann** [comment]
Ok here is something else: 

### CurseForge Description

The whole text is good. But big massive chunk of text to read for users discovering randomly(or not, maybe filtering by downloads, maybe browse > categories, maybe entering some keywords in the searchfield) addons. Ppl on average don't read, they scan quickly. (altho I am myself like reading lol) but there is like attention span and instant gratification thingie.

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/661f5b04-5113-4b15-8ef1-f0b822afa355)

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/a39a71a9-d770-487b-9d70-48c1587d5cc3)


#### Just kind of ideas to improve:

- shorten the text to the gist of the sections: intro, features, example use cases
- add some additional line breaks after each feature and/or use case to be recognised separated and be easy to read
- think about putting essential top notch image(1-2)(good big resolution, not tiny) of your addon into the overview tab, that hit the nail or nerve, analogue to the above the fold hero section of a website, where visitors decide to scroll down or pass after tiny seconds of impression. Ppl would already be served with that information beforehand instead of requiring to click the screenshots tab. 

Something like this, yet text not shortened, cause up to you, addon author :D You define the length, tone and mood of your text for all the wow audience. Just some impressions to reflect on.

### Example Use Cases:

- Leveling Profile: Create a profile named "Leveling" tailored for your journey through Azeroth's vast landscapes and quests. This profile can include addons that enhance quest tracking, provide detailed maps, or offer valuable insights into NPC locations and objectives. By activating the "Leveling" profile, you ensure that only addons contributing to an efficient leveling experience are loaded, keeping your UI clean and focused.

- Gathering Profile: Enables addons relevant to professions such as Mining, Herbalism, and Skinning, focusing your UI on gathering activities.


- Raiding Profile: Set up a "Raiding" profile for those intense raid nights. This profile would focus on addons critical for raid encounters, such as boss mechanics alerts, raid cooldown tracking, and damage meters. Switching to the "Raiding" profile ensures that you're equipped with all the necessary tools to contribute effectively to your raid team, without distractions from less relevant addons.


- PVP Profile: For players who thrive in the competitive arena of PVP, a "PVP" profile can be configured. This profile would include addons specialized in PVP scenarios, like enemy cooldown trackers, battleground tactics, and arena unit frames. By activating the "PVP" profile when entering battlegrounds or arenas, AddonSuite guarantees that your interface is optimized for victory against your adversaries.

--- 

🤔 

For the use cases, would it be possible to have my addons scanned and contextually grouped and assigned to mentioned profiles above? Maybe this could be a value and time saver for the users to have something like this at the start. Additional manipulations with these pre-created-generated based on installed addons - profiles could be thought of...

Average User:

1. Install Addon Suite
2. Log into Game
3. Open Addon Suite UI
4. Find a section with my Addons contextually grouped and assigned to profiles (gathering, pvp, raid, etc.)
or
require me manually click a button to start the automation process
5. Let me do additional operations with the profiles, like gathering is main scenario, but it will happen in a pvp area, so let me mix? or easily pick something from pvp in there. Or generate such mixed profile contextually.

Just some thoughts
