### ISSUE TITLE
Feature Request: Minimap icon with profile selection drop down

### ISSUE THREAD

**Issue by AODfan** [kapresoft/wow-addon-suite#2]
I would like to suggest a feature of a minimap icon that allows you to switch/select the different profiles from a dropdown

**Comment by nfet** [comment]
Hi There,

2024.3.2 should be available in curse forge shortly.  
https://legacy.curseforge.com/wow/addons/addon-suite/files

Here's the release notes:
https://github.com/kapresoft/wow-addon-suite/releases/tag/2024.3.2

I'm still continuing to improve the app, so please if you have more inputs ideas just open another issue/bug/feature request.

**Comment by ux-paul-grossmann** [comment]
Hey,

I would pick up on this and suggest an implementation into Titan Panel, too. 

![image](https://github.com/kapresoft/wow-addon-suite/assets/27516495/717875b0-659c-4484-9d9a-2d8722eb39a8)

**Comment by nfet** [comment]
Sounds good. I may need to change that name and remove the minimap on the name instead of AddonSuiteMinimap.

**Comment by nfet** [comment]
I changed the curse forge logo and minimap icon. I forgot to change the minimap name; heh, maybe next release.

Also, the icon will change to a red-ish tone in minimap or titan panel if out of sync.

https://legacy.curseforge.com/wow/addons/addon-suite/files/5255605

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/2e45c989-5e33-48bf-86b7-e8fca5feda14)
