### ISSUE TITLE
Current profile displayed on Titan bar

### ISSUE THREAD

**Issue by msc6399** [kapresoft/wow-addon-suite#39]
Doing great work with this addon so far.  Something I would like to see is the
name of the current profile next to he addon icon.  Only the name because space
can become a premium on the bars.  Attached screenshot shows what would really 
make this stand out.  You would have the icon and next to it (in this example) Naye-World.
Looking at the screenshot, looking to the left of your icon, you will see an example of what
I mean.  This addon (TalentBroker) shows the current spec (Marksman) and the current talent
set (Single). And as your addon, these can be changed by left and/or right clicking on the icon.
Keep it up and thanks!
![WoWScrnShot_041824_160242](https://github.com/kapresoft/wow-addon-suite/assets/34355842/3a258b2b-17de-439a-9a66-31eccb55eb76)

**Comment by nfet** [comment]
Excellent idea. Would you be fine with providing an option to truncate? Like show ellipses (...) if it is larger than N settings.  There are cases where I use the shortbar instead of the top or bottom bars.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/39755141-f109-4ad9-bfdc-89e1ccb68de6)

**Comment by msc6399** [comment]
Not sure what your asking.  But eliminating the character name and just showing addon set would work i.e.
instead of Naye-World, would be World.  You already know what character you're on unless you use one set for multiple characters.  But then the player should know this.

**Comment by nfet** [comment]
If profile name is "Druid-Heals-On-Wednesday-Raids-H", would be truncated to "Druid-Heals-On-Wednesday...", if it exceeds the configured max.  This way, the feature also works on short titan bars. Maybe set the default value to 20 characters before it truncates the profile name.

Without Ellipses:
![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/de2831c6-48ed-4e16-866f-f96cbc4b963c)

With Ellipses:
![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/09d89f14-61b8-4f39-9323-ba6c0bdfe072)

**Comment by msc6399** [comment]
I don't think I would go to all that trouble.  If I had a set named "Druid-Heals-On-Wednesday-Raids-H", then I would truncate it myself to something like "DHOW-RH".  But that's me.  Again, I just would like to see what I suggested.  I tend to keep my naming simple.  Again, keep it up.
