### ISSUE TITLE
Where to donate

### ISSUE THREAD

**Issue by msc6399** [kapresoft/wow-addon-suite#45]
Where on Paypal can I make a donation?  Must have missed something because I couldn't find you.
Also, thanks for the work you have put into this project.  I see there are more downloads building up.
You're getting there.
Thanks!

**Comment by nfet** [comment]
I find this type of work really engaging and the more I understand the wow APIs the faster I can code. Thank you for suggesting ideas. I have four addons and it keeps me really busy 😁.

In the addon site, there is a donate button. It should take you to a paypal donation page that will have my name 'Antonio Lagnada'. I think I mentioned before that there's no need to donate but I sincerely appreciate it.

https://www.curseforge.com/wow/addons/addon-suite/

![20240419_154608.jpg](https://github.com/kapresoft/wow-addon-suite/assets/1599306/67aa11cf-b93f-4c9e-abfd-df330c39419c)
