### ISSUE TITLE
Synchronized enabled addons checklist against current enabled/disabled addons state

### ISSUE THREAD

**Issue by nfet** [kapresoft/wow-addon-suite#5]
When the user closes the settings dialog which addon checklist updated, 
the addon should synchronize enabled addons checklist against current enabled/disabled addons state
and prompt the user to reload with a list of addons that need to be enabled or disabled.

Possible Features
- [x] I would like to be prompted to reload (if configured to do so) after closing the settings UI if my addons "enabled/disabled" state is out of sync
- [x] I would like to have a color or character indicator when an addon is not in it's current state (enabled or disabled) so that the player is informed that a reload is required to activate the out-of-sync addons

**Comment by msc6399** [comment]
Doing great so far.  Are you still working on synchronizing the addon with existing addons per character?
I have attached a screenshots
showing what I am talking about.  The addons were already enabled but were not
picked up by AddonSuite.  Thanks!
![World Of Warcraft Screenshot 2024 03 29 - 11 45 15 42](https://github.com/kapresoft/wow-addon-suite/assets/34355842/12ea50ee-a51d-4f1c-bf67-97f47bc1cee8)
![World Of Warcraft Screenshot 2024 03 29 - 11 45 39 82](https://github.com/kapresoft/wow-addon-suite/assets/34355842/0e475f54-d301-400a-9292-c739d169fa31)

**Comment by nfet** [comment]
Yes. This is my next priority. Thanks.

**Comment by msc6399** [comment]
Execellent! Keep up the great work.

**Comment by nfet** [comment]
Just FYI: I should be able to work on this starting tomorrow.
