### ISSUE TITLE
Addon causing game freezes.

### ISSUE THREAD

**Issue by msc6399** [kapresoft/wow-addon-suite#50]
I have the addon on my Titan Panel bar and have not had any problems with it.  However, with the latest update of 5/7/24, whenever you hover on the addon the game will freeze for about 40secs.  If you right click to goto the profile , the game will freeze for up to a minute or hang altogether.  I get the same results with only Titan Panel and Addon Suite enabled.  
You've done great work with this project and know you can find the solution.
Thanks!

**Comment by nfet** [comment]
I also use this addon on the daily basis and have not experienced what you mentioned.   I will need to investigate and profile.

What version of WoW are you using, BTW so I can try and repro on the same version hopefully.

**Comment by nfet** [comment]
I enabled all my addons and profiled (and tried to repro what you've described above. Addon Usage shows a very low CPU and mem usage.   Try and install "Addon Usage" as well so I can get a better direction on what to fix if any.  Thank you in advance.

The Addon Usage stats below is for my character in Cata.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/288af53a-b437-4cdf-bbd3-d35419304e00)

**Comment by nfet** [comment]
I installed the Curse Forge version for Wow Cata and same low cpu and mem profile.

**Comment by nfet** [comment]
I've verified CPU and Mem usage for Classic Era and Retail and same low cpu and mem profile.

**Comment by msc6399** [comment]
It says the War Within but it's the same before the last update.  Here is what's happening.![WoWScrnShot_050924_061850](https://github.com/kapresoft/wow-addon-suite/assets/34355842/da742c73-7ae9-48be-b8dd-d25a1ea7efbc)
![WoWScrnShot_050924_061915](https://github.com/kapresoft/wow-addon-suite/assets/34355842/0f2f0986-1c44-48ec-b1a4-b0520fab1f60)
![WoWScrnShot_050924_061928](https://github.com/kapresoft/wow-addon-suite/assets/34355842/533d9ee7-04ca-44a8-8f46-37dbac099a57)

**Comment by nfet** [comment]
Thanks. Will take a look.

**Comment by nfet** [comment]
Not related to this issue, but how did you adjust the buffs to go lower than the titan panel?  Mine is overlapping.  Thanks in advance.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/b6190df9-67b7-4d86-95fa-91f8e5a013fc)

**Comment by nfet** [comment]
I'm still not able to repro on Retail with Addon Usage.  I suspect Addon Usage and some other addon together may be causing this delay.  I have an idea of how to make it more efficient. I just need a repro case to verify the fix.  I will try to install the same addon as what I'm seeing on the screenshots.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/bcb64a15-43bf-443c-a5be-ce863d1d9a8a)

**Comment by nfet** [comment]
I've installed the addons that I could see on the screen shot and I have like a lot installed now. I continuously hovered around the Addon Suite icon on the titan panel and just navigate around the addon settings to see if I can repro and no luck so far.  I will continue to investigate.   I'm testing this on Addon Suite v. 2024.4.15.

In the meantime, could I get you to create a new profile (without copying an existing one) or reset the existing profile in the profiles tab? I'm wondering if there's corrupted data that is causing this.

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/348ff705-e682-46df-8caa-7fe522648a96)

![image](https://github.com/kapresoft/wow-addon-suite/assets/1599306/f8d25fc4-3259-4e54-bdff-352986e3f7e8)

**Comment by nfet** [comment]
One more request, only enable titan panel addons, addon usage and addon suite and see what you get.   Do you also have another addon manager enabled?  Thank you for doing this.  I will be glad to fix as soon as I get more data.

**Comment by msc6399** [comment]
Disabled everything except Addon Suite and Addon Usage.  Here is a video that might help see what is happening.  I am right clicking on the minimap button.  Don't be fooled about the speed of change.  Don't know why it looks normal but the actual time from when I click on the button until you see the addon page is actually around 40-50 secs.  Hope this helps.  Again, everything was working fine until this last update.  This is my play around Youtube page.
https://youtu.be/MSy9QbHxd2Y

**Comment by nfet** [comment]
I still can't repro. I am putting this on the back burner for now.  I won't be able to fix what I can't repro. My biggest apology. Please downgrade to the version that works for you for now until I can allocate time to fix.

**Comment by msc6399** [comment]
I understand.  Can't fix what you can't see.  4.6 works like it should.  Any version beyond that freezes.
Like I said earlier, everything was working fine until the last update.  Although "The Wrath Within" is not out yet I think they are doing things in prep that has affected your addon.  Thanks for your help.

**Comment by nfet** [comment]
I just signed up for the World of Warcraft®: The War Within™  Beta Access. If approved, I'll be able to hopefully reproduce.

**Comment by msc6399** [comment]
I see you have found what Blizz broke on your addon.  Nice job. Thanks!

**Comment by kapresoft** [comment]
I just went through an optimization and fixed other things [edit] in the process. I
take [edit] it's all working for you now? My apologies it too this long.

Also looks like i need to buy the most expensive upgrade to get into the
beta.

Thanks and cheers,
